version: 2

snapshots:
  - name: dim_team
    description: "Dimension for rugby teams"
    columns:
      - name: team_sk
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  # - name: stadium
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         - not_null

  # - name: country
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         - not_null

  # - name: team
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         - not_null